version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: humo_postgres
      POSTGRES_DB: msu
    ports:
      - "5432:5432"
  msu-scholarship:
    build:
      dockerfile: Dockerfile     
    restart: always 
    environment:    
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres 
      DB_PASSWORD: humo_postgres  
      DB_NAME: msu  
    ports:
      - "8081:8080" 
    depends_on:
      - db 